SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 50
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.05  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 5000
PLAYER_SPEED = 6000
PLAYER_SHOT_SPEED = 10000
PLAYER_SHOOT_COOLDOWN = 0.03 # seconds

SHOT_RADIUS = 5