SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 50
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 1  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 500
PLAYER_SPEED = 600
PLAYER_SHOT_SPEED = 800
PLAYER_SHOOT_COOLDOWN = 0.3 # seconds

SHOT_RADIUS = 5